In [1]:
import numpy as np
import pandas as pd

In [2]:
nums = np.array([2,4,6,8,9])
print(type(nums))
print(nums)

<class 'numpy.ndarray'>
[2 4 6 8 9]


In [9]:
# Vectorized operations
print(nums*2)
print(nums/2)
print(nums**2)    # power 2
print(nums)    # the above operations do not change any of the above

[ 4  8 12 16 18]
[1.  2.  3.  4.  4.5]
[ 4 16 36 64 81]
[2 4 6 8 9]


In [11]:
num2 = np.array([2,4,'list'])
print(num2)          # prints everything as string, since the array has various types

['2' '4' 'list']


In [18]:
# 2x3 array
num3 = np.array([[1,2,3], [4,5,6]])
print(num3)
num3.dtype   # data type

[[1 2 3]
 [4 5 6]]


dtype('int64')

In [21]:
num3.ndim   # ndim is the no. of dimensions

2

In [23]:
num3.shape

(2, 3)

In [24]:
num3.size

6

In [26]:
# iteration  ----> since the dimention is 2 we have to iterate both rows and columns
for row in num3:
    for column in row:
        print(column, end="-")
    print()

1-2-3-
4-5-6-


In [31]:
# flatten the array --> making it to 1 dimension
for e in num3.flat:
    print(e, end=' ')

num3.flat

1 2 3 4 5 6 

#### Filling and Creating

In [33]:
d = np.zeros(5)
print(d)

[0. 0. 0. 0. 0.]


In [41]:
#3x2 array containing only 1 value
d = np.full((3,2), 22)
print(d)

[[22 22]
 [22 22]
 [22 22]]


In [63]:
# creating with range functions
np.arange(1, 20, 5)   # ARANGE can also be written like the following linspace code

array([ 1,  6, 11, 16])

In [49]:
# evenly spaced/linearly spaced floats
np.linspace(start=1, stop=20, num=9)

array([ 1.   ,  3.375,  5.75 ,  8.125, 10.5  , 12.875, 15.25 , 17.625,
       20.   ])

In [52]:
# reshape the array
np.linspace(start=1, stop=20, num=12).reshape(3,4)

array([[ 1.        ,  2.72727273,  4.45454545,  6.18181818],
       [ 7.90909091,  9.63636364, 11.36363636, 13.09090909],
       [14.81818182, 16.54545455, 18.27272727, 20.        ]])

#### Operation and Calculations

In [60]:
print(f"{num3*2}\n")
print(f"{num3**3}\n")
num3 + num3

[[ 2  4  6]
 [ 8 10 12]]

[[  1   8  27]
 [ 64 125 216]]



array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [112]:
# broadcasting and some methods
grades = np.array([[75,59,60], [100, 85, 92],
                [55, 78, 93], [14,88,65]])
print(grades)
grades.shape

[[ 75  59  60]
 [100  85  92]
 [ 55  78  93]
 [ 14  88  65]]


(4, 3)

In [113]:
print(f"Mean: {grades.mean()}")
print(f"Sum: {grades.sum()}")
print(f"Max: {grades.max()}")
print(f"std: {round(grades.std(),2)}")

Mean: 72.0
Sum: 864
Max: 100
std: 22.56


#### Calculations by Rows or columns

In [114]:
print(f"Mean: {grades.mean(axis = 0)}")    # gets average of each columns

Mean: [61.  77.5 77.5]


In [115]:
print(f"Mean: {grades.mean(axis = 1)}")    # gets average of each row

Mean: [64.66666667 92.33333333 75.33333333 55.66666667]


#### BroadCasting and rules

In [116]:
print(grades/2)     # works since the digit 2 is stretched to the grade.shape()

[[37.5 29.5 30. ]
 [50.  42.5 46. ]
 [27.5 39.  46.5]
 [ 7.  44.  32.5]]


In [117]:
print(grades+grades)  # works cuz they have same shape doesn't have to be same list

[[150 118 120]
 [200 170 184]
 [110 156 186]
 [ 28 176 130]]


#### Slicing and indexing

In [118]:
print(grades)
print(grades[3,1])  # prints 1 specific needed no.

[[ 75  59  60]
 [100  85  92]
 [ 55  78  93]
 [ 14  88  65]]
88


In [119]:
print(grades[2,])  # prints 3rd row
print(grades[:,2]) # prints 3rd, column must have : in it or else it will be syntax
print(grades[0:2, 2]) # figure this out later

[55 78 93]
[60 92 93 65]
[60 92]


#### Shallow Copying

In [121]:
marks = grades.view()
print(marks)
# if any edits are made to the grades, then marks is also changed

[[ 75  59  60]
 [100  85  92]
 [ 55  78  93]
 [ 14  88  65]]


In [124]:
marks +=2
print(grades)
print(marks)     # and yes if marks is changed, then so does grades like a pointer

[[ 81  65  66]
 [106  91  98]
 [ 61  84  99]
 [ 20  94  71]]
[[ 81  65  66]
 [106  91  98]
 [ 61  84  99]
 [ 20  94  71]]


#### Slice view()

In [126]:
d = np.arange(1,6)
d_slice = d[:3]
print(d)
print(d_slice)
print(id(d))
print(id(d_slice))

[1 2 3 4 5]
[1 2 3]
5375876080
5370623632


In [127]:
d += 10
print(d)
print(d_slice)

[11 12 13 14 15]
[11 12 13]


In [128]:
d_slice -= 10
print(d)
print(d_slice)

[ 1  2  3 14 15]
[1 2 3]


#### Deep Copy

In [131]:
d_copy = d.copy()
print(d_copy)
d_copy +=2         # creates an idividual duplicate, doesn't link both 
print(d_copy)
print(d)

[ 1  2  3 14 15]
[ 3  4  5 16 17]
[ 1  2  3 14 15]
